### PR TITLE
issue #51, changed and added integer/string handling functions + some tests

### PR DESCRIPTION
**Pull request by jeras**
I added most new function declarations, replaced all use cases for old functions, added macros for deprecated functions, added corner case tests.

This code now compiles without errors, but it is possible some functions are defined but not implemented.

I tested the next functions and the 64 bit versions are failing for now:
SCPI_Int32ToStr
SCPI_UInt32ToStr
SCPI_Int64ToStr
SCPI_UInt64ToStr
How do you debug this code, do you have a CLI to run unit tests in gdb?

The code is ready for the first review of at least for the first discussion, I probably made too many copies of similar code. I still have to run a proper check against a table of functions, fix some probable issues with short strings for 64 bit types and write some more tests. Please tell me if there is something else I should fix.

### CODE REVIEW

**Comment by j123b567** [comment]
> I added most new function declarations, replaced all use cases for old functions, added macros for deprecated functions, added corner case tests.

Nice!

> This code now compiles without errors, but it is possible some functions are defined but not implemented.

OK

> I tested the next functions and the 64 bit versions are failing for now:
> SCPI_Int32ToStr
> SCPI_UInt32ToStr
> SCPI_Int64ToStr
> SCPI_UInt64ToStr
> How do you debug this code, do you have a CLI to run unit tests in gdb?

I'm writing bug free code :D, no just kidding. I'm using printf, gdb, if it is really bad bug, I use some IDE like Netbeans.

Conversions are little bit tricky. These constants are maximum number, that not overflow the type and are calculated as base^n. For signed 64bit and base 10, n=18, and for unsigned, n=19, because n=20 overflows the datatype. Calculating these numbers for other bases is similar.

I've created a pull request to your branch to pass all tests.

> The code is ready for the first review of at least for the first discussion, I probably made too many copies of similar code. I still have to run a proper check against a table of functions, fix some probable issues with short strings for 64 bit types and write some more tests. Please tell me if there is something else I should fix.

I think, that there is no need to have two `ParamToInt32` and `ParamToUInt32`. For `base != 10` numbers are always unsigned and for base 10, it is safe to mix signed and unsigned types as I did. But if you think, that it is bad, please remove parameter `sign` and internal casts to (uint32_t/int32_t) from these functions and keep them both. (same for UInt64/Int64)

Similarly, we can have only full `SCPI_UInt64ToStr` and `SCPI_UInt32ToStr` and call these functions inside `SCPI_Int64ToStr` and `SCPI_Int32ToStr`. If signed number is negative, just print "-" and call 
`SCPI_UInt64ToStr(..., -value, ...)`.

Buffer in `SCPI_ResultUInt64Base` and `SCPI_ResultInt64Base` should be 65 bytes. Longest number is in base 2 and it is 64 numbers. Last byte is for NUL termination.

**Comment by RedPitaya** [comment]
Thanks for the int64 fixes. 

What would you use as the reference implementation for conversion to strings. For example if `snprintf` was used as reference, we could use it in the unit tests instead of providing manually calculated values.

I would also prefer to use converters from a library in the source. As far as I understand you are avoiding `printf` due to a running on an AVR32 with a minimalistic libc. There are two known implementations in libraries `snprintf` and `itoa`. Both have issues `snprintf` might be slow and consume a lot of RAM, and while `itoa` is more optimized, it is not standard. Did you think about adding a macro for switching between implementations.

I will try to combine few signed/unsigned functions.

**Comment by j123b567** [comment]
> What would you use as the reference implementation for conversion to strings. For example if `snprintf` was used as reference, we could use it in the unit tests instead of providing manually calculated values.

You are right, tests will be always executed on memory "unlimited" device, so it is possible to run tests against `snprintf`

> I would also prefer to use converters from a library in the source. As far as I understand you are avoiding `printf` due to a running on an AVR32 with a minimalistic libc. There are two known implementations in libraries `snprintf` and `itoa`. Both have issues `snprintf` might be slow and consume a lot of RAM, and while `itoa` is more optimized, it is not standard. Did you think about adding a macro for switching between implementations.

Some users run it on AVR32, my primary target is ARM Cortex-M4, but it don't mind. They are both memory limited and it is sometimes helpfull to avoid calling `printf` and `scanf`. We can add similar handling as other function to `config.h` so it is possible to use `snprintf` on linux and manual conversion on bare metal.

Yes `itoa` is not standard and there is no int64/uint64 to string conversion function at all (except snprintf).

Last call to snprintf is for conversion from string to double. I would also avoid this for next release so it can be completely printf-free release.

> I will try to combine few signed/unsigned functions.

Please do it for `SCPI_XYZToStr`.

For `ParamToInt32` and `ParamToUInt32`, it was ugly hack and you can leave your implementation with proposed cleanup.

**Comment by RedPitaya** [comment]
I now updated the tests to use strlen() for string lengths instead of constants, also snprintf is used to produce the reference string, C99 offers inttypes.h which allowed me to explicitly target 32/64 bit types, also I replaced test constant values with library marros for MIN/MAX values.

What is missing is a reference converter to binary representations, do you have any suggestions?

The compiler complained about a for loop in C99 style, so I added `-std=c99` to Makefile. This caused two new warnings in `src/utils.c`. Are you OK with compiling everything for C99 standard, or would you prefer to use the compilers default standard. I kind of expected C99 to already be the default on my platform (latest Ubuntu).

**Comment by j123b567** [comment]
C99 is nice, but it is not supported by many proprietary C compilers.

Namely:

 - Microsoft Visual C < 2015
 - Keil C compiler for ARM

To avoid this, just put declaration of `i` outside `for` and it will be ok;

Why are you using `uintptr_t` in tests? You can use just `int`.

**Comment by RedPitaya** [comment]
I used `uintptr_t` just to experiment with explicit types.

The main reason why I like C99 are https://en.wikipedia.org/wiki/Variable-length_array, which in many cases allow you to write code without malloc, which is great for bare metal code. This library is malloc free, so this is not much of an issue. I will remove the option later in a separate commit.

**Comment by j123b567** [comment]
I like C99 also, but in near past, there were lot of compilers not supporting it. 

After some investigation
 - Visual C support it from 2015
 - Kail moves to RealView that support it
 - Microchip moves to GCC so support it
 - IAR support it from 2010
 - Intel compiler support it from 2011
 - LabWindows/CVI support it from 2014

So I still don't need it, but maybe, v4.0 of scpi-parser should switch to c99 and simplify some parts of code. I must investigate, if there will be some benefits for it.

**Comment by RedPitaya** [comment]
I removed some signed/unsigned function duplication, but I did not check all functions. Some functions which are currently only wrappers could be replaced with macros.

I am not sure I used the right `x` constants in `SCPI_Int32ToStr` and `SCPI_Int64ToStr`, I copied them from the signed version for 32bit and unsigned version for 64bit, the current tests are passing, but I do not have a proper understanding of the conversion algorithm, so I am not sure how to improve test coverage. If it is obvious to you what to change, please do, otherwise I will take another look at this primary school algorithm :).

There are some warnings preset which I do not think are due to my changes, but were probably revealed by switching to the C99 standard:

```
src/utils.c: In function ‘compareStr’:
src/utils.c:262:5: warning: implicit declaration of function ‘strncasecmp’ [-Wimplicit-function-declaration]
     if (SCPIDEFINE_strncasecmp(str1, str2, len2) == 0) {
     ^
src/utils.c: In function ‘matchCommand’:
src/utils.c:428:5: warning: implicit declaration of function ‘strnlen’ [-Wimplicit-function-declaration]
     size_t cmd_len = SCPIDEFINE_strnlen(cmd, len);
     ^
```

**Comment by j123b567** [comment]
For C99 `strncasecmp` is defined in `strings.h` not in `string.h`.

`strnlen` is defined only if using `_GNU_SOURCE`. It is also possible to compile it with
`CFLAGS="-DHAVE_STRNLEN=0" make`
to avoid `strnlen` completely. It is standard, but I don't know how to correctly use it under c99.

**Comment by j123b567** [comment]
Conversion functions looks good.

I have only one note. `SCPI_ResultIntXYBase` should always behave as unsigned to the user. I have this wrong in my code, because value is stored in signed type. And it should be `SCPI_ResultUIntXYBase`.

So there should be one more function declared static. This function will be used in `SCPI_ResultUIntXYBase`, `SCPI_ResultIntXY` and `SCPI_ResultUIntXY`. Do you understand me what I want to say? And do you agreee?

So now, just `SCPI_ParamToInt64`, `SCPI_ParamToUInt64`, `SCPI_ParamInt64` and `SCPI_ParamUInt64` are missing?

**Comment by jeras** [comment]
If `SCPI_ResultIntXYBase` should be changed to `SCPI_ResultUIntXYBase`, should then I also change `SCPI_IntXYToStr` to `SCPI_IntXYToStr`?

**Comment by j123b567** [comment]
Good question.

It makes definitely sense for `SCPI_Result...` functions.

`SCPI_...ToStr` is little bit wierd. We can have one private static function without `SCPI_` prefix and with name `UIntXYToStr` and two public exported functions with `SCPI_` prefix. One for signed numbers and one for unsigned. Finally, signed version should be only for base 10.

I now don't want to dictate that it must be that or that. Finally, you will be the user of these functions, so it must sound good for you. I would like to release version 3 after these changes to warn about API changes. So now, I would like to do it right - because it was not right at v2.

Name conventions of internal functions don't mind, but
 - I don't want to have wierd public API with "sign" parameter
 - I don't want to have duplicate code, so it is possible to have these condensed functions, but just for internal use

If it doesn't make sense for you, just tell me.

**Comment by RedPitaya** [comment]
I decided for the next naming conventions:
1. if the input value is unsigned use `UInt`
2. if the function has a `base` argument append `Base`
3. if the function has a `sign` argument append `Sign`, and remove the SCPI_ prefix, and make the function static

Signed function do not have a `base` argument, while unsigned have, there are no unsigned functions without a base argument.

The latest build has problem linking, since I used some static functions from utils.c in parser.c, I used static functions, since they can handle sign, otherwise I would have to use `if (sign)` to select between signed/unsigned public functions.

What would you recommend?

**Comment by j123b567** [comment]
Nice! It sounds perfect.

You can remove `static` from `UInt32ToStrBaseSign` and friends and put prototypes in `libscpi/src/utils_private.h` with `LOCAL` modifier. Thats all.

**Comment by jeras** [comment]
I renamed some more static functions to have Base and Sign in their names, then I added 64 bit Param* functions.

I noticed another function, which is 32bit only, would it make sense to add a 64 bit version?
SCPI_ExprNumericListEntryInt

**Comment by j123b567** [comment]
It would make sense to at least rename it to Int32. There is no need to preserve old name, because this function was not released.

Introducing 64bit function would be easy.

**Comment by RedPitaya** [comment]
Travis build is failing, but I can not reproduce the same issue locally, and I tried on Ubuntu amd64 and Debian 8 ARM32. The issue is caused by my change in the unit test code for doubleToStr. where I replaced hardcoded reference values with snprintf("%g", ...). I could revert this code if this issue will continue.

**Comment by j123b567** [comment]
You have wrong compution of N on line 221
`int N = sizeof(val) / sizeof(int);`
it should be
`int N = sizeof(val) / sizeof(double);`
but it is safer to use
`int N = sizeof(val) / sizeof(val[0]);`
because it is resistant to copy/paste issues

or better, define somewhere in this file macro `countof` 
`#define countof(a) (sizeof(a) / sizeof(a[0]))`
and use everywhere
`int N = countof(val);`

**Comment by j123b567** [comment]
If you need to reproduce this, you can compile everything with `-fsanitize=address`

`CFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address" make clean test`

I'm using CLANG for this in travis, because GCC in travis does not support address sanitizer but recent GCCs support it.

**Comment by RedPitaya** [comment]
I created another commit which adds `float` functions to existing `double` functions.

Even if you find this addition unnecessary, there are a few comments I would add after reading the `double` functions sources.

In function `SCPI_ParamToDouble` in case the number is not decimal, `uint32_t` conversion is used, I would suggest using `uint64_t`. This is already part of the commit.

Function `SCPI_ResultDouble` reserves 32 characters for the buffer, while in unit tests 50 characters are reserved. I was looking for a minimum number for `%lg` formatting and found this post:
http://stackoverflow.com/questions/1701055/what-is-the-maximum-length-in-chars-needed-to-represent-any-double-value
One of the posters mentioned 24 characters without NULL, otherwise the post is confusing, focusing on `%lf` formatting, which can be much longer. Did you use something more specific for reference?

This buffers for integer buffers example could be made shorter depending on the used integer base, this should be relatively easy in C99.


Otherwise this branch should be ready for pulling now, do you see any open issues? Probably some more corner cases for floating point numbers could be tested, and the added Result* Parameter* functions could also be tested, but I did not see an obvious test to copy.

I would like to move to other issues now :)

**Comment by j123b567** [comment]
> I created another commit which adds `float` functions to existing `double` functions.

Perfect!

> Even if you find this addition unnecessary, there are a few comments I would add after reading the `double` functions sources.

> In function `SCPI_ParamToDouble` in case the number is not decimal, `uint32_t` conversion is used, I would suggest using `uint64_t`. This is already part of the commit.

This sounds reasonable

> Function `SCPI_ResultDouble` reserves 32 characters for the buffer, while in unit tests 50 characters are reserved. I was looking for a minimum number for `%lg` formatting and found this post:
http://stackoverflow.com/questions/1701055/what-is-the-maximum-length-in-chars-needed-to-represent-any-double-value
One of the posters mentioned 24 characters without NULL, otherwise the post is confusing, focusing on `%lf` formatting, which can be much longer. Did you use something more specific for reference?

I don't have any better reference. There will be some more work, because of introducing our own double to string conversion function. But it is another topic. So choose sizes of buffers as you think it is the best.

> This buffers for integer buffers example could be made shorter depending on the used integer base, this should be relatively easy in C99.

I would like to keep this version compatible with C89/C90. We can stabilize current functions for this version and introduce optimized version using C99 later.

> Otherwise this branch should be ready for pulling now, do you see any open issues? Probably some more corner cases for floating point numbers could be tested, and the added `Result*`, `Parameter*` functions could also be tested, but I did not see an obvious test to copy.

I will check it little bit and merge it.

> I would like to move to other issues now :)

Thank you very much for this cleanup and extension.

**Comment by jeras** [comment]
I rebased all changes for a cleaner history tree.

**Pull request merged**
