### PR TITLE
Update register implementation

### PR DESCRIPTION
**Pull request by PolyPik**
This PR both removes the recursive function calls in SCPI_RegSet and allows library users to add their own device-specific registers to the parser.

### CODE REVIEW

**Comment by PolyPik** [comment]
@j123b567 Basically this closes this [TODO](https://github.com/j123b567/scpi-parser/blame/a077a73a54ee0e789d7f39fc1587f20cb0cfd545/libscpi/src/ieee488.c#L127) and #81.

**Comment by j123b567** [comment]
Thank you, I will investigate this PR. I must also verify this against SCPI-99, because this PR seems OK, but sometimes SCPI see it differently. So, just to be sure.


Just a hint for further contributions, please create separate branch for each PR. All your new commits to your master will go into this PR automatically, which could be unintentional.

**Comment by PolyPik** [comment]
Is it good?

**Comment by PolyPik** [comment]
@j123b567 Is there an ETA?

**Comment by PolyPik** [comment]
I'm going to make an identical PR using a non-master branch.

**Pull request closed without merging**
